package com.aiqibaowork.entity;

import lombok.Data;

import java.util.Date;
@Data
public class PassengerRegisterSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.passenger_info_id
     *
     * @mbg.generated
     */
    private Integer passengerInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.register_source
     *
     * @mbg.generated
     */
    private String registerSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.market_channel
     *
     * @mbg.generated
     */
    private String marketChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_register_source.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.id
     *
     * @return the value of tbl_passenger_register_source.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.passenger_info_id
     *
     * @return the value of tbl_passenger_register_source.passenger_info_id
     *
     * @mbg.generated
     */
    public Integer getPassengerInfoId() {
        return passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.register_source
     *
     * @return the value of tbl_passenger_register_source.register_source
     *
     * @mbg.generated
     */
    public String getRegisterSource() {
        return registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.market_channel
     *
     * @return the value of tbl_passenger_register_source.market_channel
     *
     * @mbg.generated
     */
    public String getMarketChannel() {
        return marketChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.create_time
     *
     * @return the value of tbl_passenger_register_source.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_register_source.update_time
     *
     * @return the value of tbl_passenger_register_source.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }
}