package com.aiqibaowork.entity;

import lombok.Data;

import java.util.Date;
@Data
public class PassengerAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.passenger_info_id
     *
     * @mbg.generated
     */
    private Integer passengerInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.address_name
     *
     * @mbg.generated
     */
    private String addressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.address_desc
     *
     * @mbg.generated
     */
    private String addressDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_address.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.id
     *
     * @return the value of tbl_passenger_address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.passenger_info_id
     *
     * @return the value of tbl_passenger_address.passenger_info_id
     *
     * @mbg.generated
     */
    public Integer getPassengerInfoId() {
        return passengerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.latitude
     *
     * @return the value of tbl_passenger_address.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.longitude
     *
     * @return the value of tbl_passenger_address.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.address_name
     *
     * @return the value of tbl_passenger_address.address_name
     *
     * @mbg.generated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.type
     *
     * @return the value of tbl_passenger_address.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.address_desc
     *
     * @return the value of tbl_passenger_address.address_desc
     *
     * @mbg.generated
     */
    public String getAddressDesc() {
        return addressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.create_time
     *
     * @return the value of tbl_passenger_address.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_address.update_time
     *
     * @return the value of tbl_passenger_address.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }
}