package com.aiqibaowork.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class PassengerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.educatioan
     *
     * @mbg.generated
     */
    private String educatioan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.passenger_name
     *
     * @mbg.generated
     */
    private String passengerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.register_time
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.head_img
     *
     * @mbg.generated
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.passenger_type
     *
     * @mbg.generated
     */
    private Byte passengerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.user_level
     *
     * @mbg.generated
     */
    private Byte userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.register_type
     *
     * @mbg.generated
     */
    private Short registerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_method
     *
     * @mbg.generated
     */
    private Byte lastLoginMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_screen_time
     *
     * @mbg.generated
     */
    private Date lastLoginScreenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_login_screen_method
     *
     * @mbg.generated
     */
    private String lastLoginScreenMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.last_order_time
     *
     * @mbg.generated
     */
    private Date lastOrderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_passenger_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.id
     *
     * @return the value of tbl_passenger_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.phone
     *
     * @return the value of tbl_passenger_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.educatioan
     *
     * @return the value of tbl_passenger_info.educatioan
     *
     * @mbg.generated
     */
    public String getEducatioan() {
        return educatioan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.birthday
     *
     * @return the value of tbl_passenger_info.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.passenger_name
     *
     * @return the value of tbl_passenger_info.passenger_name
     *
     * @mbg.generated
     */
    public String getPassengerName() {
        return passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.register_time
     *
     * @return the value of tbl_passenger_info.register_time
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.balance
     *
     * @return the value of tbl_passenger_info.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.gender
     *
     * @return the value of tbl_passenger_info.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.head_img
     *
     * @return the value of tbl_passenger_info.head_img
     *
     * @mbg.generated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.passenger_type
     *
     * @return the value of tbl_passenger_info.passenger_type
     *
     * @mbg.generated
     */
    public Byte getPassengerType() {
        return passengerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.user_level
     *
     * @return the value of tbl_passenger_info.user_level
     *
     * @mbg.generated
     */
    public Byte getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.register_type
     *
     * @return the value of tbl_passenger_info.register_type
     *
     * @mbg.generated
     */
    public Short getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_time
     *
     * @return the value of tbl_passenger_info.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_method
     *
     * @return the value of tbl_passenger_info.last_login_method
     *
     * @mbg.generated
     */
    public Byte getLastLoginMethod() {
        return lastLoginMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_screen_time
     *
     * @return the value of tbl_passenger_info.last_login_screen_time
     *
     * @mbg.generated
     */
    public Date getLastLoginScreenTime() {
        return lastLoginScreenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_login_screen_method
     *
     * @return the value of tbl_passenger_info.last_login_screen_method
     *
     * @mbg.generated
     */
    public String getLastLoginScreenMethod() {
        return lastLoginScreenMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.last_order_time
     *
     * @return the value of tbl_passenger_info.last_order_time
     *
     * @mbg.generated
     */
    public Date getLastOrderTime() {
        return lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.create_time
     *
     * @return the value of tbl_passenger_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_passenger_info.update_time
     *
     * @return the value of tbl_passenger_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    private Integer isContact;

    private Integer isShare;

    private String sharingTime;
}