package com.aiqibaowork.mapper;

import com.aiqibaowork.entity.PassengerInfo;
import org.apache.ibatis.annotations.*;

public interface PassengerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tbl_passenger_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tbl_passenger_info (id, phone, ",
        "educatioan, birthday, ",
        "passenger_name, register_time, ",
        "balance, gender, ",
        "head_img, passenger_type, ",
        "user_level, register_type, ",
        "last_login_time, last_login_method, ",
        "last_login_screen_time, last_login_screen_method, ",
        "last_order_time, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{phone,jdbcType=VARCHAR}, ",
        "#{educatioan,jdbcType=VARCHAR}, #{birthday,jdbcType=DATE}, ",
        "#{passengerName,jdbcType=VARCHAR}, #{registerTime,jdbcType=TIMESTAMP}, ",
        "#{balance,jdbcType=DECIMAL}, #{gender,jdbcType=TINYINT}, ",
        "#{headImg,jdbcType=VARCHAR}, #{passengerType,jdbcType=TINYINT}, ",
        "#{userLevel,jdbcType=TINYINT}, #{registerType,jdbcType=SMALLINT}, ",
        "#{lastLoginTime,jdbcType=TIMESTAMP}, #{lastLoginMethod,jdbcType=TINYINT}, ",
        "#{lastLoginScreenTime,jdbcType=TIMESTAMP}, #{lastLoginScreenMethod,jdbcType=CHAR}, ",
        "#{lastOrderTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PassengerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_info
     *
     * @mbg.generated
     */
    int insertSelective(PassengerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, phone, educatioan, birthday, passenger_name, register_time, balance, gender, ",
        "head_img, passenger_type, user_level, register_type, last_login_time, last_login_method, ",
        "last_login_screen_time, last_login_screen_method, last_order_time, create_time, ",
        "update_time",
        "from tbl_passenger_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.aiqibaowork.mapper.PassengerInfoMapper.BaseResultMap")
    PassengerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PassengerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_info
     *
     * @mbg.generated
     */
    @Update({
        "update tbl_passenger_info",
        "set phone = #{phone,jdbcType=VARCHAR},",
          "educatioan = #{educatioan,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=DATE},",
          "passenger_name = #{passengerName,jdbcType=VARCHAR},",
          "register_time = #{registerTime,jdbcType=TIMESTAMP},",
          "balance = #{balance,jdbcType=DECIMAL},",
          "gender = #{gender,jdbcType=TINYINT},",
          "head_img = #{headImg,jdbcType=VARCHAR},",
          "passenger_type = #{passengerType,jdbcType=TINYINT},",
          "user_level = #{userLevel,jdbcType=TINYINT},",
          "register_type = #{registerType,jdbcType=SMALLINT},",
          "last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP},",
          "last_login_method = #{lastLoginMethod,jdbcType=TINYINT},",
          "last_login_screen_time = #{lastLoginScreenTime,jdbcType=TIMESTAMP},",
          "last_login_screen_method = #{lastLoginScreenMethod,jdbcType=CHAR},",
          "last_order_time = #{lastOrderTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PassengerInfo record);

    PassengerInfo queryPassengerInfoByPhoneNum(String phone) ;

}