package com.aiqibaowork.mapper;

import com.aiqibaowork.entity.PassengerRegisterSource;
import org.apache.ibatis.annotations.*;

public interface PassengerRegisterSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int insert(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int insertSelective(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    PassengerRegisterSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PassengerRegisterSource record);
}