package com.aiqibaowork.mapper;

import com.aiqibaowork.entity.PassengerAddress;
import org.apache.ibatis.annotations.*;

public interface PassengerAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tbl_passenger_address",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tbl_passenger_address (id, passenger_info_id, ",
        "latitude, longitude, ",
        "address_name, type, ",
        "address_desc, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{passengerInfoId,jdbcType=INTEGER}, ",
        "#{latitude,jdbcType=DOUBLE}, #{longitude,jdbcType=DOUBLE}, ",
        "#{addressName,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{addressDesc,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PassengerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbg.generated
     */
    int insertSelective(PassengerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, passenger_info_id, latitude, longitude, address_name, type, address_desc, ",
        "create_time, update_time",
        "from tbl_passenger_address",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.aiqibaowork.mapper.PassengerAddressMapper.BaseResultMap")
    PassengerAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PassengerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_address
     *
     * @mbg.generated
     */
    @Update({
        "update tbl_passenger_address",
        "set passenger_info_id = #{passengerInfoId,jdbcType=INTEGER},",
          "latitude = #{latitude,jdbcType=DOUBLE},",
          "longitude = #{longitude,jdbcType=DOUBLE},",
          "address_name = #{addressName,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "address_desc = #{addressDesc,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PassengerAddress record);
}