package com.aiqibaowork.mapper;

import com.aiqibaowork.entity.PassengerWallet;
import org.apache.ibatis.annotations.*;

public interface PassengerWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_wallet
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tbl_passenger_wallet",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_wallet
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tbl_passenger_wallet (id, passenger_info_id, ",
        "capital, give_fee, ",
        "freeze_capital, freeze_give_fee, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=INTEGER}, #{passengerInfoId,jdbcType=INTEGER}, ",
        "#{capital,jdbcType=DOUBLE}, #{giveFee,jdbcType=DOUBLE}, ",
        "#{freezeCapital,jdbcType=DOUBLE}, #{freezeGiveFee,jdbcType=DOUBLE}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PassengerWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_wallet
     *
     * @mbg.generated
     */
    int insertSelective(PassengerWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_wallet
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, passenger_info_id, capital, give_fee, freeze_capital, freeze_give_fee, create_time, ",
        "update_time",
        "from tbl_passenger_wallet",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.aiqibaowork.mapper.PassengerWalletMapper.BaseResultMap")
    PassengerWallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_wallet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PassengerWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_wallet
     *
     * @mbg.generated
     */
    @Update({
        "update tbl_passenger_wallet",
        "set passenger_info_id = #{passengerInfoId,jdbcType=INTEGER},",
          "capital = #{capital,jdbcType=DOUBLE},",
          "give_fee = #{giveFee,jdbcType=DOUBLE},",
          "freeze_capital = #{freezeCapital,jdbcType=DOUBLE},",
          "freeze_give_fee = #{freezeGiveFee,jdbcType=DOUBLE},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PassengerWallet record);
}