package com.aiqibaowork.mapper;

import com.aiqibaowork.entity.PassengerRegisterSource;
import org.apache.ibatis.annotations.*;

public interface PassengerRegisterSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tbl_passenger_register_source",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tbl_passenger_register_source (id, passenger_info_id, ",
        "register_source, market_channel, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=INTEGER}, #{passengerInfoId,jdbcType=INTEGER}, ",
        "#{registerSource,jdbcType=VARCHAR}, #{marketChannel,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbg.generated
     */
    int insertSelective(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, passenger_info_id, register_source, market_channel, create_time, update_time",
        "from tbl_passenger_register_source",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.aiqibaowork.mapper.PassengerRegisterSourceMapper.BaseResultMap")
    PassengerRegisterSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbg.generated
     */
    @Update({
        "update tbl_passenger_register_source",
        "set passenger_info_id = #{passengerInfoId,jdbcType=INTEGER},",
          "register_source = #{registerSource,jdbcType=VARCHAR},",
          "market_channel = #{marketChannel,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PassengerRegisterSource record);
}